---
- name: Ensure dependencies (Debian/Ubuntu)
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: yes

- name: Create keyrings directory
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"

- name: Add Docker’s official GPG key
  get_url:
    url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
    dest: /etc/apt/keyrings/docker.gpg
    mode: "0644"


# Para Ubuntu/Debian, construímos a linha do repo com signed-by
- name: Set Docker apt repository
  apt_repository:
    repo: "deb [arch={{ 'arm64' if ansible_facts['architecture'] in ['aarch64','arm64'] else 'amd64' }} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/{{ ansible_facts['distribution'] | lower }} {{ ansible_facts['distribution_release'] }} stable"
    state: present
    filename: docker
    update_cache: yes

- name: Remove old docker packages (if any)
  apt:
    name:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    state: absent
  ignore_errors: yes

- name: Install Docker engine (Debian/Ubuntu)
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: "{{ docker_package_state }}"
    update_cache: yes
